package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;

public class ContactCreationTests extends TestBase{
    private WebDriver driver;


    @Test
    public void CanCreationContact() {
        app.CreateContact(new ContactData("egor", "fedotov", "arzamas", "88005553535", "egor@gmail.com"));
    }

    @Test
    public void CanCreationContactEmpty() {
        app.CreateContact(new ContactData());
    }

    @Test
    public void CanCreateContactWithNameOnly() {
        app.CreateContact(new ContactData().withName("IVAN"));
    }
}
