package tests;// Generated by Selenium IDE

import model.ContactData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;

public class ContactCreationTests extends TestBase{
    private WebDriver driver;


    @Test
    public void CanCreationContact() {
        int countContacts = app.contacts().getCount();
        app.contacts().CreateContact(new ContactData("egor", "fedotov", "arzamas", "88005553535", "egor@gmail.com"));
        int newCountContacts = app.contacts().getCount();
        Assertions.assertEquals(countContacts + 1, newCountContacts);
    }

    @Test
    public void CanCreationContactEmpty() {
        app.contacts().CreateContact(new ContactData());
    }

    @Test
    public void CanCreateContactWithNameOnly() {
        app.contacts().CreateContact(new ContactData().withName("IVAN"));
    }
}
