package tests;// Generated by Selenium IDE

import model.ContactData;
import model.GroupData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;

public class ContactCreationTests extends TestBase{
    private WebDriver driver;


    @Test
    public void CanCreationContact() {
        int countContacts = app.contacts().getCount();
        app.contacts().CreateContact(new ContactData("egor", "fedotov", "arzamas", "88005553535", "egor@gmail.com"));
        int newCountContacts = app.contacts().getCount();
        Assertions.assertEquals(countContacts + 1, newCountContacts);
    }

    @Test
    public void CanCreationContactEmpty() {
        app.contacts().CreateContact(new ContactData());
    }

    @Test
    public void CanCreateContactWithNameOnly() {
        app.contacts().CreateContact(new ContactData().withName("IVAN"));
    }

    @Test
    public void CanCreateMultipleContact() {
        int n = 5;
        int countContacts = app.contacts().getCount();
        for(int i = 0; i < n; i++){
            app.contacts().CreateContact(new ContactData(randomString((i+1)*10), "fedotov", "arzamas", "88005553535", "egor@gmail.com"));
        }
        int newCountContacts = app.contacts().getCount();
        Assertions.assertEquals(countContacts + n, newCountContacts);
    }
}

